version: '3'
services:
  recipeapp:
    image: recipe-api
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - recipepostgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://recipepostgres:5432/recipe
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  recipepostgres:
    image: postgres
    restart: always
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=recipe