
server:
  port: 8080
  max-http-header-size: 48000
  servlet:
    context-path: /api/recipe/v1/
    encoding:
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

# ========= Logging ==========
logging:
  level:
    root: DEBUG
    com:
      crediteurope: DEBUG
